#Name of entire workflow
name: Shell Commands

#After name we define events which will trigger the workflow

on: [push] # it can be array of events

#Git hosted runner
jobs: 
    run-shell-command:
      runs-on: ubuntu-latest
      #put example of self hosted for explaining the case of VM runner
      steps:
        - name: echo a string
          run: echo "Testing an echo command"
        - name: multiline script
          run: |
            node -v
            npm -v
    run-github-actions:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout branch
          uses: actions/checkout@v1
        - name: simple JS Action
          id: greet
          uses: actions/hello-world-javascript-action@v1
          with:
            who-to-greet: Faizy
        - name: Log Greeting Time
          run: echo "${{ steps.greet.outputs.time }}"
